name: charity_project_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #Design
  text_scroll: 0.2.0
  flutter_svg: 2.0.10+1
  vector_graphics: 1.1.11
  vector_graphics_compiler: 1.1.11

  #Responsive
  flutter_screenutil: 5.9.3
  auto_size_text: 3.0.0
  #Utils
  country_picker: 2.0.27
  uniform: 2.0.7
  faker: ^2.2.0

  #Translation
  easy_localization: 3.0.8
  intl: 0.20.2

  #State Management
  flutter_bloc: 8.1.3
  equatable: 2.0.7
  reactive_forms: ^18.1.1

  #Navigation
  go_router: ^14.6.2

  #Camera
  camerawesome: ^2.5.0
  path_provider: ^2.1.5

  #Image Viewer
  photo_view: ^0.15.0
  permission_handler: ^11.3.1

  #Voice Recording
  audio_waveforms: ^1.0.5

  #network
  http: ^1.2.2

  #Storage
  shared_preferences: ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.0
  freezed: ^3.0.0
  flutter_gen_runner: ^5.11.0
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/lottie/
    - assets/translation/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/bebas_neue/BebasNeue-Regular.ttf

flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    image: true
    flutter_svg: true
